name: Publish Docker images

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:

  build-gpt4all-cli:
    uses: localagi/ai-dedicated-workflows/.github/workflows/operation-docker-build-publish.yml@v3
    with:
      registry-repo-name: gpt4all-cli
      dockerfile: Dockerfile.cli
      context-repository: nomic-ai/gpt4all
      context-repository-ref: ${{ github.ref }}
      tags: |
        type=schedule
        type=ref,event=branch
        type=semver,pattern={{version}}
      platforms: linux/amd64,linux/arm64/v8
    secrets: inherit
