name: Publish Docker images

on:
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo gpt4all
        uses: actions/checkout@v4
        with:
          repository: nomic-ai/gpt4all
          path: gpt4all
          ref: main
          
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          path: main
        
      - name: Login docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: test
        run: ls -la

      - name: build and push
        uses: docker/build-push-action@v6
        with:
          context: ./gpt4all
          file: ./main/Dockerfile
          push: true
          tags: gpt4all:latest
